--- 
env:
  docker:
    Dockerfile: |
      FROM debian:testing
      ENV DEBIAN_FRONTEND noninteractive
      RUN apt-get update && apt-get install -y build-essential golang
fpm: ["-dfpm", "-ddocker"]
fpm-hooks:
  after-install: |
    #!/bin/bash
    set -e
    systemctl enable --no-block fpmbot.timer
    systemctl start --no-block fpmbot.timer
    systemctl enable --no-block fpmbot.service
